# Generated by Django 5.2.11 on 2026-03-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
        ('users', '0002_authority_area_authorityrequest_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assigned_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.authority'),
        ),
    ]
