# Generated by Django 5.2.14 on 2026-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityrequest',
            name='pincode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
