# Generated by Django 5.2.11 on 2026-03-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='authorityrequest',
            name='area',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
