# Generated by Django 5.2.11 on 2026-03-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authorityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='authority',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizen',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
