# Generated by Django 5.2.11 on 2026-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authority_is_online_authority_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizen',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
